### PR TITLE
fix #154 no background sound on SEGA RALLY CHAMPIONSHIP

### LINKED ISSUE #154: [Alone In The Dark 1 - Eyed Jack's Revenge (U)] Freeze on the Imotion logo
Yabause 05.05.2016 (Software)

The game freezes at the start on the Imotion logo.

### PR DESCRIPTION
**Pull request by devmiyax**
Hi there,
This is a patch from uoYabause.
https://github.com/devmiyax/yabause/issues/154

(cherry picked from commit 7b49752d54f911656e3f27b30421a7664a435928)

### CODE REVIEW

**Comment by d356** [comment]
CyberWarriorX says "the fix should only be applied to track mode." Does the game still work if that change is made?

**Comment by devmiyax** [comment]
Actually I didn't test all of game. (^^; , but most of games program data is stored inside of track1. Then the effect of this change is very limited. 

Since in the cd_ctrl.c(SEGA Offical cd cntrol smaple) CD-DA is played with the code below, my implementation is not wrong.

```C
/*** Play Music. ***/
void	PlayMusic( int track ){

    CDC_PLY_STNO( &playdata ) = (Uint8) track;
    CDC_PLY_ETNO( &playdata ) = (Uint8) track;
    CDC_CdPlay(&playdata);
}
```

**Comment by cyberwarriorx** [comment]
Hey devmiyax, sorry I misread the change at first. But I still don't understand. Is not 

`if ((pdepos & 0xFF) == 0)
         Cs2Area->playendFAD = Cs2TrackToFAD((u16)(pdepos | 0x0063));`

essentially doing the same thing? Also how is this affecting values other than start track == end track?

**Comment by devmiyax** [comment]
```
if ((pdepos & 0xFF) == 0)
```
is the cause of this problem.  At the opening of SegaRally the pdepos value is 0x0201. 
Then
```
Cs2Area->playendFAD = Cs2TrackToFAD((u16)pdepos);
```
is called.


Do you think this code should be like this?
```
  else if (pdepos != 0)
  {
       Cs2Area->playendFAD = Cs2TrackToFAD((u16)(pdepos | 0x0063));
  }
```

**Comment by cyberwarriorx** [comment]
Normally it should use the index position if it exists and is in range. Default value of 0 is supposed to use index 1 for start position and 99 for end position. But considering we're not handling index anyways at this point might maybe it might be best to assume index is 1 for start pos and 99 for end pos.

**Comment by cyberwarriorx** [comment]
Will fix in post

**Pull request merged**
