### PR TITLE
Openal Soundcore

### PR DESCRIPTION
**Pull request by Amon-X**
This changes the Openal sound from pthreads to yabause threads. This allows the openal sound core to be used in windows. Please note you need hardware specific / optimized openal for decent performance. I tested this in Debian 8 and was able to get normal sound using NVidia display drivers instead of the mesa nouveau ones (most likely due to NVidia drivers using less CPU). 
Edit: something I came across the "free version of OpenAL is not hardware accelerated"

### CODE REVIEW

**Comment by BenjaminSiskoo** [comment]
I compiled last sources. Any option to use this ? In the sound tab, I just have Dummy Sound Interface and SDL Sound Interface.

**Comment by Amon-X** [comment]
In cmake YAB_WANT_OPENAL and make sure cmake can find openal. I used openal soft. In visual studios you make need to use the linker option /OPT:NOREF

**Comment by BenjaminSiskoo** [comment]
In cmake YAB_WANT_OPENAL is checked.

Do I need to download openal library ?
If yes, there is a line in Cmake to add it ?

thanks by advance

**Comment by Amon-X** [comment]
There are a few different versions of openal I used this version http://kcat.strangesoft.net/openal.html#download 
If you install it and add it to your path cmake should be able to find it or on windows at least just download and extract the zip folder and if using cmake gui hit the advanced checkmark and make sure OPENAL_INCLUDE_DIR and OPENAL_LIBRARY are defined ie c:/openal-soft-1.17.2-bin/include/ and c:/openal-soft-1.17.2-bin/libs/Win64/OpenAL32.lib 

Let me know if you need more info

**Comment by BenjaminSiskoo** [comment]
Thanks for your time. Your last message was perfectly clear :) .I've got some error messages.  I guess this stuff is important : "In visual studios you make need to use the linker option /OPT:NOREF", could you explain to me how to do this ^^ !!!

**Comment by Amon-X** [comment]
I am currently at work so I am going off memory. There is a cmake line where you can add it but I just went to the project properties - > configuration -> linker -> command line and there is a place to add it. Yabause should have the option /machine just add /OPT:NOREF after. For some reason it is only needed with openal. 
On Mar 2, 2016 6:01 AM, BenjaminSiskoo <notifications@github.com> wrote:Thanks for your time. Your last message was perfectly clear :) .I've got some error messages.  I guess this stuff is important : "In visual studios you make need to use the linker option /OPT:NOREF", could you explain to me how to do this ^^ !!!

**Comment by BenjaminSiskoo** [comment]
Take your time. Too bad, I can't find the linker. Could you guide me step by step ? Open VS, .....

**Comment by Amon-X** [comment]
Try taking a look at the pictures http://www.steptools.com/support/stdev_docs/help/settings_vc10.html open vs right click on yabause qt go to properties. I'll be at work for a while let me know if this helps. 
On Mar 2, 2016 10:13 AM, BenjaminSiskoo <notifications@github.com> wrote:Take your time. Too bad, I can't find the linker. Could you guide me step by step ? Open VS, .....

**Comment by Amon-X** [comment]
In cmake under advanced look for CMAKE_EXE_LINKER_FLAGS and you can add 
/OPT:NOREF there if you still cant find the linker options. Here is a 
screenshot http://imgur.com/FIzbN3N after right clicking on yabause-qt 
and then going to properties. Note this is in Visual Studio 2010 
Ultimate and the GUI may be different in other versions :)

**Comment by BenjaminSiskoo** [comment]
Perfect (cmake and VS), thanks :). Now here some errors messages (in English : unresolved external symbol ....  referenced in function .....) : 

Erreur	1	error LNK2019: symbole externe non résolu __imp__alGetError référencé dans la fonction _SNDALInit	C:\Yabause\Yabause-Officiel\src\qt\yabause.lib(sndal.obj)	yabause-qt
Erreur	2	error LNK2019: symbole externe non résolu __imp__alGenSources référencé dans la fonction _SNDALInit	C:\Yabause\Yabause-Officiel\src\qt\yabause.lib(sndal.obj)	yabause-qt
Erreur	3	error LNK2019: symbole externe non résolu __imp__alDeleteSources référencé dans la fonction _SNDALInit	C:\Yabause\Yabause-Officiel\src\qt\yabause.lib(sndal.obj)	yabause-qt
Erreur	4	error LNK2019: symbole externe non résolu __imp__alSourcef référencé dans la fonction _SNDALInit	C:\Yabause\Yabause-Officiel\src\qt\yabause.lib(sndal.obj)	yabause-qt
Erreur	5	error LNK2019: symbole externe non résolu __imp__alSource3f référencé dans la fonction _SNDALInit	C:\Yabause\Yabause-Officiel\src\qt\yabause.lib(sndal.obj)	yabause-qt
Erreur	6	error LNK2019: symbole externe non résolu __imp__alSourcei référencé dans la fonction _SNDALInit	C:\Yabause\Yabause-Officiel\src\qt\yabause.lib(sndal.obj)	yabause-qt
Erreur	7	error LNK2019: symbole externe non résolu __imp__alGetSourcei référencé dans la fonction _sound_update_thd	C:\Yabause\Yabause-Officiel\src\qt\yabause.lib(sndal.obj)	yabause-qt
Erreur	8	error LNK2019: symbole externe non résolu __imp__alSourcePlay référencé dans la fonction _SNDALInit	C:\Yabause\Yabause-Officiel\src\qt\yabause.lib(sndal.obj)	yabause-qt
Erreur	9	error LNK2019: symbole externe non résolu __imp__alSourceStop référencé dans la fonction _SNDALDeInit	C:\Yabause\Yabause-Officiel\src\qt\yabause.lib(sndal.obj)	yabause-qt
Erreur	10	error LNK2019: symbole externe non résolu __imp__alSourcePause référencé dans la fonction _SNDALMuteAudio	C:\Yabause\Yabause-Officiel\src\qt\yabause.lib(sndal.obj)	yabause-qt
Erreur	11	error LNK2019: symbole externe non résolu __imp__alSourceQueueBuffers référencé dans la fonction _SNDALInit	C:\Yabause\Yabause-Officiel\src\qt\yabause.lib(sndal.obj)	yabause-qt
Erreur	12	error LNK2019: symbole externe non résolu __imp__alSourceUnqueueBuffers référencé dans la fonction _sound_update_thd	C:\Yabause\Yabause-Officiel\src\qt\yabause.lib(sndal.obj)	yabause-qt
Erreur	13	error LNK2019: symbole externe non résolu __imp__alGenBuffers référencé dans la fonction _SNDALInit	C:\Yabause\Yabause-Officiel\src\qt\yabause.lib(sndal.obj)	yabause-qt
Erreur	14	error LNK2019: symbole externe non résolu __imp__alDeleteBuffers référencé dans la fonction _SNDALInit	C:\Yabause\Yabause-Officiel\src\qt\yabause.lib(sndal.obj)	yabause-qt
Erreur	15	error LNK2019: symbole externe non résolu __imp__alBufferData référencé dans la fonction _SNDALInit	C:\Yabause\Yabause-Officiel\src\qt\yabause.lib(sndal.obj)	yabause-qt
Erreur	16	error LNK2019: symbole externe non résolu __imp__alcCreateContext référencé dans la fonction _SNDALInit	C:\Yabause\Yabause-Officiel\src\qt\yabause.lib(sndal.obj)	yabause-qt
Erreur	17	error LNK2019: symbole externe non résolu __imp__alcMakeContextCurrent référencé dans la fonction _SNDALInit	C:\Yabause\Yabause-Officiel\src\qt\yabause.lib(sndal.obj)	yabause-qt
Erreur	18	error LNK2019: symbole externe non résolu __imp__alcDestroyContext référencé dans la fonction _SNDALInit	C:\Yabause\Yabause-Officiel\src\qt\yabause.lib(sndal.obj)	yabause-qt
Erreur	19	error LNK2019: symbole externe non résolu __imp__alcOpenDevice référencé dans la fonction _SNDALInit	C:\Yabause\Yabause-Officiel\src\qt\yabause.lib(sndal.obj)	yabause-qt
Erreur	20	error LNK2019: symbole externe non résolu __imp__alcCloseDevice référencé dans la fonction _SNDALInit	C:\Yabause\Yabause-Officiel\src\qt\yabause.lib(sndal.obj)	yabause-qt
Erreur	21	error LNK1120: 20 externes non résolus	C:\Yabause\Yabause-Officiel\src\qt\Release\yabause.exe	yabause-qt

**Comment by Amon-X** [comment]
It seems like yabause lib isn't linking against openal.

**Comment by Amon-X** [comment]
Okay I figured your linker errors out. In cmake in OPENAL_LIBRARY change Win64 to Win32
32bit windows 
c:/openal-soft-1.17.2-bin/libs/Win32/OpenAL32.lib 
64bit windows
Cmake OPENAL_LIBRARY should be c:/openal-soft-1.17.2-bin/libs/Win64/OpenAL32.lib

**Comment by BenjaminSiskoo** [comment]
Still better but some more errors ^^ Erreur	1	error LNK2026: module unsafe pour l'image SAFESEH.	C:\Users\Siskoo\Desktop\Yabause-Officiel\src\qt\OpenAL32.lib(dclvbs00058.o)	yabause-qt
Erreur	2	error LNK2026: module unsafe pour l'image SAFESEH.	C:\Users\Siskoo\Desktop\Yabause-Officiel\src\qt\OpenAL32.lib(dclvbs00037.o)	yabause-qt
Erreur	3	error LNK2026: module unsafe pour l'image SAFESEH.	C:\Users\Siskoo\Desktop\Yabause-Officiel\src\qt\OpenAL32.lib(dclvbs00019.o)	yabause-qt
Erreur	4	error LNK2026: module unsafe pour l'image SAFESEH.	C:\Users\Siskoo\Desktop\Yabause-Officiel\src\qt\OpenAL32.lib(dclvbs00120.o)	yabause-qt
Erreur	5	error LNK2026: module unsafe pour l'image SAFESEH.	C:\Users\Siskoo\Desktop\Yabause-Officiel\src\qt\OpenAL32.lib(dclvbs00105.o)	yabause-qt
Erreur	6	error LNK2026: module unsafe pour l'image SAFESEH.	C:\Users\Siskoo\Desktop\Yabause-Officiel\src\qt\OpenAL32.lib(dclvbs00122.o)	yabause-qt
Erreur	7	error LNK2026: module unsafe pour l'image SAFESEH.	C:\Users\Siskoo\Desktop\Yabause-Officiel\src\qt\OpenAL32.lib(dclvbs00084.o)	yabause-qt
Erreur	8	error LNK2026: module unsafe pour l'image SAFESEH.	C:\Users\Siskoo\Desktop\Yabause-Officiel\src\qt\OpenAL32.lib(dclvbs00110.o)	yabause-qt
Erreur	9	error LNK2026: module unsafe pour l'image SAFESEH.	C:\Users\Siskoo\Desktop\Yabause-Officiel\src\qt\OpenAL32.lib(dclvbs00115.o)	yabause-qt
Erreur	10	error LNK2026: module unsafe pour l'image SAFESEH.	C:\Users\Siskoo\Desktop\Yabause-Officiel\src\qt\OpenAL32.lib(dclvbs00108.o)	yabause-qt
Erreur	11	error LNK2026: module unsafe pour l'image SAFESEH.	C:\Users\Siskoo\Desktop\Yabause-Officiel\src\qt\OpenAL32.lib(dclvbs00112.o)	yabause-qt
Erreur	12	error LNK2026: module unsafe pour l'image SAFESEH.	C:\Users\Siskoo\Desktop\Yabause-Officiel\src\qt\OpenAL32.lib(dclvbs00117.o)	yabause-qt
Erreur	13	error LNK2026: module unsafe pour l'image SAFESEH.	C:\Users\Siskoo\Desktop\Yabause-Officiel\src\qt\OpenAL32.lib(dclvbs00034.o)	yabause-qt
Erreur	14	error LNK2026: module unsafe pour l'image SAFESEH.	C:\Users\Siskoo\Desktop\Yabause-Officiel\src\qt\OpenAL32.lib(dclvbs00016.o)	yabause-qt
Erreur	15	error LNK2026: module unsafe pour l'image SAFESEH.	C:\Users\Siskoo\Desktop\Yabause-Officiel\src\qt\OpenAL32.lib(dclvbs00006.o)	yabause-qt
Erreur	16	error LNK2026: module unsafe pour l'image SAFESEH.	C:\Users\Siskoo\Desktop\Yabause-Officiel\src\qt\OpenAL32.lib(dclvbs00133.o)	yabause-qt
Erreur	17	error LNK2026: module unsafe pour l'image SAFESEH.	C:\Users\Siskoo\Desktop\Yabause-Officiel\src\qt\OpenAL32.lib(dclvbs00150.o)	yabause-qt
Erreur	18	error LNK2026: module unsafe pour l'image SAFESEH.	C:\Users\Siskoo\Desktop\Yabause-Officiel\src\qt\OpenAL32.lib(dclvbs00134.o)	yabause-qt
Erreur	19	error LNK2026: module unsafe pour l'image SAFESEH.	C:\Users\Siskoo\Desktop\Yabause-Officiel\src\qt\OpenAL32.lib(dclvbs00151.o)	yabause-qt
Erreur	20	error LNK2026: module unsafe pour l'image SAFESEH.	C:\Users\Siskoo\Desktop\Yabause-Officiel\src\qt\OpenAL32.lib(dclvbs00132.o)	yabause-qt
Erreur	21	error LNK1281: Impossible de générer l'image SAFESEH.	C:\Users\Siskoo\Desktop\Yabause-Officiel\src\qt\Release\yabause.exe	yabause-qt

**Comment by Amon-X** [comment]
From chopchop1 from irc :) goto properties - > configuration ->Linker -> Advanced and change "Image Has Safe Exception Handlers" to "No (/SAFESEH:NO)"

**Comment by BenjaminSiskoo** [comment]
Perfect, it works. Thanks to Chopchop1 and you. Now, you said p"lease note on Windows openal runs very slowly but may run fine if you have a creative sound card and use official drivers". My sound card is a creative sound blaster Audigy 2 ZS. And it runs slowly. Here my report ^^

**Comment by Amon-X** [comment]
Official creative drivers?

**Comment by BenjaminSiskoo** [comment]
Yup, SBAX_PCDRV_LB_2_18_0017.

**Comment by Amon-X** [comment]
How is Yabauses CPU usage when using openal sound core vs directx or sdl?

**Comment by BenjaminSiskoo** [comment]
OpenAL : around 56-58 %
SDL : around 30-32 %

**Comment by Amon-X** [comment]
Mind testing it with this? http://steamcommunity.com/sharedfiles/filedetails/?id=353333739 there should be a link for openal.zip just place the openal32.dll inside the yabause folder and let me know if it runs full speed. It worked for me. Be careful with the download link I think it is the second buttom.

**Comment by BenjaminSiskoo** [comment]
It doesn't works. Maybe some options to check in cmake ?

**Comment by Amon-X** [comment]
I think I figured it out. Give this dll a try Ben https://drive.google.com/file/d/0B_sr4bv3Y7KXT1VhNDNEWlYzNVk/view?usp=sharing it should be the same as the 64bit version that works for me I just am not set up to build the 32bit version of yabause so I can test it

**Comment by BenjaminSiskoo** [comment]
Sounds good. CPU usage is around 65 %. But no more slowdown. congrats. Any differences about OpenAL and SDL ?

**Pull request merged**
