### PR TITLE
vidsoft: improve sonic 2 two player mode

### PR DESCRIPTION
**Pull request by d356**
This game updates the vertical cell scroll table and map registers mid frame.
jam1

jam2

### CODE REVIEW

**Comment by BenjaminSiskoo** [comment]
Left Picture : Yabause 03.23.2016 (Software)
Left Picture : Yabause 03.24.2016 (Software) (with this fix)

now the game crash.

true pinball

**Comment by Mori-S** [comment]
That's True Pinball by ocean for anyone else might want to know

**Comment by BenjaminSiskoo** [comment]
Yup, forget to add the name :)

**Comment by Mori-S** [comment]
That's okay, I got you covered : )

**Comment by BenjaminSiskoo** [comment]
thanks \o/ :p

**Comment by d356** [comment]
I can't reproduce a crash. I checked the U and E versions of the game on windows and linux.

**Comment by BenjaminSiskoo** [comment]
No problem with U version. Just with E (built in bios and real bios)

**Comment by Zetchzie** [comment]
this is on Sonic Jam right?

**Comment by d356** [comment]
@BenjaminSiskoo I just checked E again, no crash. If you're using savestates, they tend to cause crashes. Otherwise I would need information on where the crash is occuring in the code to fix it.
@Zetchzie Yeah

**Comment by BenjaminSiskoo** [comment]
I'm not using savestates (sound problem with). Tomorrow, I'll get last sources, add your code (maybe it will be up). And i'll try it again :)

By the way, thanks to improve vidsoft.

**Comment by Mori-S** [comment]
@BenjaminSiskoo Does this have any effect on space harrier? Wonder what other games it could fix. It seems like something they'd use for other ports of system16 / genesis stuff

**Comment by BenjaminSiskoo** [comment]
Except True Pinball (regression or not). I tested several games (Space Harrier, Touge King Of Spirit, Resident Evil, Doom, Blam Machine and much more...) and there is no regression/improvements.

**Comment by Mori-S** [comment]
dang that's too bad, thanks for that

**Comment by BenjaminSiskoo** [comment]
I got the last sources with the sonic fix (Merge pull request #199 from d356/sonic-fix). I still have a crash with the european game of True Pinball. To answer to your question, after pushing start, you can see the table (like the left picture). With this fix, you can't see the table, it crash just before.

**Comment by d356** [comment]
I'm going to need information like this to fix it: debugging

**Comment by BenjaminSiskoo** [comment]
I would like, but I have no more info. No error message in the yabause log. I tested another image. Same problem. I don't know how to do. A video ?

**Comment by d356** [comment]
Set visual studio to a debug build.
debug12
Build yabause.
Press the "Local Windows Debugger" button, play the game until it crashes.
Show me the exception dialog, the breakpoint in the code, and the Call Stack like the image in the previous post.

**Comment by BenjaminSiskoo** [comment]
- After pushing start, there is a message :  this project is obsolete  -->  c68kinc - RelWithDebInfo Win32
Do you want to generate again. After pushing yes, there is another message. Impossible to start the program --> C:\....\ RelWithDebInfo\ALLBUILD. Specified file is not found.
- I start the game with the RelWithDebug. and no crash. 
- I found a small problem with Qt interface with the RelWithDebug. --> Debug --> Memory Editor --> The close cross is grey (inactive).

**Comment by d356** [comment]
For the first problem you need to set yabause-qt as the startup project.
dbug3

**Comment by BenjaminSiskoo** [comment]
Ok it works. The game works with RelWithDebInfo. And not with the Release one ^^.

Here the link to the archive. http://www.tradu-france.com/download.php?emul=139

Could you test it ? (Yabause 32 Bits - Windows)

**Comment by d356** [comment]
Could you replace TestSpriteWindow in vidsoft.c with this and try it?

```C
int TestSpriteWindow(int wctl, int x, int y)
{
   int mask;
   int addr;

   if ((y >= 512) || (x >= 704)) return 0;

   addr = (y*vdp1width) + x;

   if (addr >= (704 * 512))
      return 0;

   mask = sprite_window_mask[addr];

   if (wctl & 0x20)//sprite window enabled on layer
   {
      if (wctl & 0x10)//inside or outside
      {
         if (mask == 0)
            return 0;
      }
      else
      {
         if (mask)
            return 0;
      }

      return 1;
   }
   return 3;
}
```

If that doesn't work, try this:

```C
int TestSpriteWindow(int wctl, int x, int y)
{
   return 0;
}
```

**Comment by BenjaminSiskoo** [comment]
The first code is ok. Thank you. Fixed :)

**Pull request merged**
