### PR TITLE
scsp: implement new slot generation method with fm support

### PR DESCRIPTION
**Pull request by d356**
An example of the difference can be heard in this video: https://raw.githubusercontent.com/d356/yabause-ci-test/master/scsp-fm.mp4 The fm sounds in the bios are played on the current scsp followed by this one.

The new scsp is enabled with the USE_NEW_SCSP define because it is still missing some features.

### CODE REVIEW

**Comment by BenjaminSiskoo** [comment]
I would like to test it. I have to set something in cmake or VS ?

**Comment by d356** [comment]
You can put #define USE_NEW_SCSP at the top of scsp.c to test it. However some sounds aren't going to be correct until I implement some missing features.

**Comment by BenjaminSiskoo** [comment]
Thanks. Tested. If you need some game with missing sound/music. I could give you a list. Are you trying to improve the sound/music ?

**Comment by d356** [comment]
Most missing sounds and music due to unimplemented features, so I would recommend waiting until those features are implemented.

**Comment by BenjaminSiskoo** [comment]
No problem. I just give you my help if needed :)

**Pull request merged**
