### PR TITLE
new scsp / qt: add plfo, alfo, ssf playing

### PR DESCRIPTION
**Pull request by d356**
LFO improves Nights and Shinobi X. The ssf player is based on https://github.com/cyberwarriorx/yabber and aosdk.

### CODE REVIEW

**Comment by BenjaminSiskoo** [comment]
Burning Rangers and some other games crash with these fixes..

**Comment by d356** [comment]
Burning Rangers seems to be working fine for me.

**Comment by BenjaminSiskoo** [comment]
I'm waiting for the merge. And I'll try it again... Thanks for your quik answer

**Comment by BenjaminSiskoo** [comment]
I made a fresh install (delete all file). And Burning Rangers still crashes (cue or bin).

**Comment by d356** [comment]
The SSF player shouldn't make a difference. I need to see the call stack like described here: https://github.com/devmiyax/yabause/issues/205

**Comment by BenjaminSiskoo** [comment]
Fixed

**Pull request merged**
