### PR TITLE
Android es3

### PR DESCRIPTION
**Pull request by devmiyax**
Hi,

I've merged my OpenGL ES 3.0 VIDCORE to your master.it work like following.
https://youtu.be/484umZ0UrI0

This patch contents below.
* add OpenGL ES 3.0 VIDCORE
* use OpenSL Sound core.( When I forked, AudioTrack Sound core didn't work.)
* add GLFW port which is useful for ES 3.0 debug on the desktop. it's just for debug.
* better( not best ) Android touchpad ui.
* add setting Interface for   VIDCORE selection.

What I've confirmed are below.
*  works fine Nexus7(2013).
*  can build android, gtk, qt, glfw ports on Linux
*  can build qt,glfw ports on Windows.
*  There are no regressions to play 'Nights' 'Daytona USA' 'VirtuaFighter2' 

What I've NOT confirmed are below.
* can build on Mac.

I'll be happy you accept this patch and I can't wait to see Yabause works on new NVIDIA SHEILD.
Sega Saturn come back again to Living rooms!

### CODE REVIEW

**Comment by Guillaumito** [comment]
Hey devmiyax o/

First of all, thanks for this pull request!

I've spent some time rewiewing it and there's a lot of work in this and a lot of interesting things too.
Now, there's a few things I don't like, for instance the duplicate nanovg in the sources. I'm also pretty sure it breaks some ports. But the most important thing is the yglcache.cpp file, as it means there's C++ in the emulation core... and we don't want C++ in the emulation library :) Moreover I can't even get it to compile for Android, so I didn't had a chance to test it.

So what I would like to do is to merge your branch in a new "android_es3" in our repository, so I can start fixing some things, while keeping in sync with your branch. We could then merge it to the master branch when all details have been fixed. Is it ok for you?

**Comment by Guillaumito** [comment]
Ok... I created a android_es3 branch in the Yabause repository and I started to push my changes...

**Comment by ADormant** [comment]
Any chance for a newer OpenGL version working on Windows?

**Comment by cyberwarriorx** [comment]
The windows port will pull in whatever is on the main branch and is usable on windows.

**Comment by cyberwarriorx** [comment]
We currently don't have a build bot.

**Comment by devmiyax** [comment]
I create another pull request to android_es3 branch.
It's ok to close this pull request.

**Pull request closed without merging**
