### PR TITLE
Enumerate each command table in QT VDP1 debug window

### PR DESCRIPTION
**Pull request by ijacquez**
Not a fix, but a simple change to enumerate all command tables in VDP1 debug.

It's also nice to know how many command tables are being processed :)

### CODE REVIEW

**Comment by cyberwarriorx** [comment]
gtk code needs updating to support reworked function.

**Comment by ijacquez** [comment]
No problem.

I wasn't aware that the GTK+ port is still active.

I'll update soon, thanks.

**Comment by cyberwarriorx** [comment]
It isn't active from what I know of, but I can't remember whether it was going to be removed or what the plan was. It's still in the cmake build though and until it's removed from that there's always a chance someone will want to compile it and find out they can't.

**Comment by cyberwarriorx** [comment]
So just to follow up, talked to Guill and gtk+ code is definitely deprecated and will be removed. So don't worry about it.

**Pull request merged**
